### ISSUE TITLE
How to measure time?

### ISSUE THREAD

**Issue by pedromxavier** [psrenergy/QUBOTools.jl#18]
We currently let the sampler tell us the time it took during optimization, as in:
```julia
function Anneal.sample(annealer::Optimizer{T}) where {T}
    sampler = neal.SimulatedAnnealingSampler()

    t₀ = time()
    records = sampler.sample_qubo(
        annealer.Q;
        num_reads=MOI.get(annealer, MOI.RawOptimizerAttribute("num_reads")),
        num_sweeps=MOI.get(annealer, MOI.RawOptimizerAttribute("num_sweeps")),
    ).record
    samples = [(pyconvert.(Int, s), pyconvert(Int, n), pyconvert(Float64, e + annealer.c)) for (s, e, n) in records]
    t₁ = time()

    δt = t₁ - t₀

    return (samples, δt)
end
```
Shouldn't we care about the sampling only and measure time automatically from outside of the `Anneal.sample` call, taking initialization and data formatting into account?

**Comment by bernalde** [comment]
Their official answer to a user like us https://support.dwavesys.com/hc/en-us/community/posts/360038385054-measuring-QPU-access-time

**Comment by pedromxavier** [comment]
Thanks for the pointer @bernalde! What I'm concerned now is about the format of the `"time"` entry of our `SampleSet`'s `metadata`. We could follow D-Wave's but I think it is preferrable to include it instead (as bqpjson does)

Currently, we are (informally) using something like: (example from [QuantumAnnealingInterface.jl](https://github.com/psrenergy/QuantumAnnealingInterface.jl))
```julia
metadata = Dict{String, Any}(
    "time" => Dict{String, Any}(
        "total" => 1.0235124,
        "simulation" => 0.78292,
        "measurement" => 0.0023,
        "sampling" => 0.0195,
    )
)
```
I wish we had a standard for it, in order to align all sorts of solvers/samplers. It would also be great to hear from @ccoffrin in this matter.

**Comment by pedromxavier** [comment]
There is a bigger discussion about the `metadata` contents as a whole. I've also included a `origin` field to indicate the solver/method used to obtain that sample set.
Having standards for that would be great (JSONSchema would be fantastic).
I mean, there is a lot of stuff defined in bqpjson for dwave-specific solutions; I'm thinking cross-platform here.
