### ISSUE TITLE
Implement fixed-size SampleSet

### ISSUE THREAD

**Issue by pedromxavier** [psrenergy/QUBOTools.jl#20]
The `ExactSampler` searches $2^n$ states but it is interesting to hold only a few. This could be implemented using a Heap.

**Comment by bernalde** [comment]
How would you decide which samples to take and how would this be different from the RandomSampler?

**Comment by pedromxavier** [comment]
That's a good question, @bernalde. We defined an ordering by lowest energy followed by highest sampling frequency as a tie-breaker. The first idea is to take the $k$ "best" samples. I'm not sure if this is a globally good idea since this may throw shadow on heavy-tailed or multimodal distributions.

The problem, in fact, has to do with samplers like the `ExactSampler` whose search visits _too many_ states. For some dimension values $n$ around a sweet spot it still feasible to exaustively visit every node but there is no memory to store them all.

**Comment by pedromxavier** [comment]
My suggestion is to add a `size::Union{Int, Nothing}` field and a `push!(::SampleSet, ...)` method.

If `size` is `nothing`, then it would behave as usual. Otherwise, it would be something like:

```julia
function push!(sampleset, sample)
    if length(sampleset) < sampleset.size
        insertsorted!(sampleset, sample)
    else
        if sample.value < sampleset[end].value
            pop!(sampleset)
            insertsorted!(sampleset, sample)
        end
    end
end
```

**Comment by bernalde** [comment]
Assuming an arbitrary problem, the sorted is just an ordering that can be meaningless, but I agree someone might be interested in only getting some samples in a given order.
