### ISSUE TITLE
Set different colors for stacked bars when plotting

### ISSUE THREAD

**Issue by pedroripper** [psrenergy/QUBOTools.jl#31]

**Comment by bernalde** [comment]
What are we plotting? Can you attach a plot example of what you are proposing?

**Comment by pedromxavier** [comment]
Sure,
<img width="468" alt="image" src="https://user-images.githubusercontent.com/31925649/230121210-01932a1b-5c23-4a67-a6cd-a962e5423240.png">

**Comment by bernalde** [comment]
Oh, sure! Different colors makes sense
