### ISSUE TITLE
Add model density visualization recipe

### ISSUE THREAD

**Issue by pedromxavier** [psrenergy/QUBOTools.jl#35]
Add plot recipe to display the $Q$ matrix according to the magnitude (and sign maybe?) of its entries.

## Example
![image](https://user-images.githubusercontent.com/31925649/236578408-de3fc7ad-11ed-456f-9c0c-9019130cb942.png)

**Comment by bernalde** [comment]
Signs and magnitudes would be great! I would just remove the grid as in large models it will be hard to read.
