### ISSUE TITLE
Add function for computing Hamming distance between solution state vectors

### ISSUE THREAD

**Issue by pedromxavier** [psrenergy/QUBOTools.jl#37]
## Rationale
This measurement is useful to determine how far, in terms of state flips, a solution is from another, e.g., the groud state.

## Suggestion
```julia
function hamming(x::Vector{U}, y::Vector{U}) where {U<:Integer}
    return count(x .!= y)
end
```

## Example
```julia
julia> x = [0, 1, 0];

julia> y = [1, 1, 0];

julia> hamming(x, y)
1
```

**Comment by bernalde** [comment]
I guess that for our applications, this implementation suffices, but usually, to compute this super efficiently, one can use bitwise operations. Check this discussion https://discourse.julialang.org/t/fast-hamming-distance-function-in-julia-that-returns-a-distance-matrix/55716
