### ISSUE TITLE
QUBOTools + MathOptInterface Wrapper for ToQUBO.jl and QUBODrivers.jl

### ISSUE THREAD

**Issue by pedromxavier** [psrenergy/QUBOTools.jl#45]
As pointed out in #34, both [`ToQUBO.jl`](https://github.com/psrenergy/ToQUBO.jl) and [`QUBODrivers.jl`](https://github.com/psrenergy/QUBODrivers.jl) will import [`MathOptInterface.jl`](https://github.com/jump-dev/MathOptInterface.jl) and implement a couple methods to integrate MOI with `QUBOTools.jl`.

```julia
function QUBOTools.varlt(x::MOI.VariableIndex, y::MOI.VariableIndex)
    ...
end

function QUBOTools.sense(s::MOI.OptimizationSense)
    ...
end
```

Currently, both packages contain the same *wrapper* code. 

```mermaid
%%{init: {'theme':'neutral'}}%%
flowchart LR;
    subgraph QUBO ["QUBO.jl"]
        direction LR;
        
        MOI(["MathOptInterface.jl"]);
        
        subgraph TOQUBO["ToQUBO.jl"]
            direction LR;
            TOQUBOWRAPPER["wrapper"];
        end
        
        MOI -..-> TOQUBOWRAPPER;
        
        subgraph QUBODRIVERS["QUBODrivers.jl"]
            direction LR;
            
            QUBODRIVERSWRAPPER["wrapper"];
        end
        
        PBO(["PBO.jl"]);
        QUBOTOOLS(["QUBOTools.jl"]);
        
        MOI -..-> QUBODRIVERSWRAPPER;
        
        QUBOTOOLS -.-> QUBODRIVERS;
        QUBOTOOLS -.-> TOQUBO;
        PBO -.-> QUBOTOOLS;
    end
```

When both are loaded in the same session, as done by [QUBO.jl](https://github.com/psrenergy/QUBO.jl), the Julia compiler will warn about method redefinition and its impact in incremental compilation. Checking for definitions using `hasmethod` fails since the wrapped functions provide dispatch options on more abstract types, including `Any`. The ideal solution would be put the *wrapper* inside a module that would be imported by both packages. This could be done by creating an extra package or by using [Package Extensions](https://pkgdocs.julialang.org/v1/creating-packages/#Conditional-loading-of-code-in-packages-(Extensions)), which impose the drawback of requiring Julia 1.9 or greater.

```mermaid
%%{init: {'theme':'neutral'}}%%
flowchart LR;
    subgraph QUBO ["QUBO.jl"]
        direction LR;
        
        MOI(["MathOptInterface.jl"]);
        
        subgraph QUBOTOOLS["QUBOTools.jl"]
            direction LR;
            
            WRAPPER["wrapper"];
        end
        
        PBO(["PBO.jl"]);
        QUBODRIVERS(["QUBODrivers.jl"]);
        TOQUBO(["ToQUBO.jl"]);

        MOI -.-> WRAPPER;

        WRAPPER -.-> QUBODRIVERS;
        WRAPPER -.-> TOQUBO;
        PBO -.-> QUBOTOOLS;
    end
```

Another option would be to simulate C/C++'s `#ifndef` behavior using a hook defined by QUBOTools.jl or even environment variables.

**Comment by bernalde** [comment]
The last option is the one I like the least; it does not seem to be a simple thing to do.
Given that Julia 1.9 is the latest stable version of Julia, and their long-term support goes back only to 1.6.7; I don't think it is such a big deal to ask for that version of Julia.
I will pass this question to @joaquimg as he's the exert in MOI.

**Comment by pedromxavier** [comment]
The last one is very simple (yet very fragile):

```julia
if get(ENV, "QUBOTOOLS_MOI_WRAPPER", "0") != "1"
    function QUBOTools.varlt(...)
        ...
    end
    
    ENV["QUBOTOOLS_MOI_WRAPPER"] = "1"
end
```
